### ISSUE TITLE
Mac M1 cannot run docker 

### ISSUE THREAD

**Issue by hernanif1** [mirego/accent#289] opened 2022-03-30 07:15 UTC
running this command 
```sh
docker run --env-file .env -p 4000:4000 mirego/accent --platform linux/amd64
```

I see this error:
```sh
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
Segmentation fault
```

according to docker contributor the container should supply an arm64 or multi-arch image:
https://github.com/docker/for-mac/issues/5123#issuecomment-784992589

**Comment by simonprev** [comment] 2022-08-29 11:56
This is a duplicate of this: https://github.com/mirego/accent/issues/304

I will do the follow up on this issue instead 👍

**Closed by simonprev** 2022-08-29 11:56 UTC
