### ISSUE TITLE
Every translations are marked as a conflict on each push

### ISSUE THREAD

**Issue by guyaumetremblay** [mirego/accent#330] opened 2022-12-13 14:40 UTC
Hi,

Each time we push our translation file (without modification), 91.25% of our strings return in status `In review` . 
In the `Activities` tab, I saw an item saying that a conflict happen on 89 strings. I did try to pull, mark everything again in `reviewed` and push again (in that order or in every other order possible) but they are marked again as in conflict and in reviewed. I also tried to rollback the conflict in the activity but it did come back after another push. 
Finally, I tried to create a version of the translations and push the file again but it doesn't work either. 

NB: We are using Accent (hosted on accent2.mirego.com) with Circumflex. 

Are you aware of this kind of situation?

Best regards

**Comment by ChiefORZ** [comment] 2023-07-03 16:03
same issue here

**Comment by simonprev** [comment] 2024-03-25 01:21
@guyaumetremblay From what I got from expecting your project in the database, it looks like sync operation are syncing english text for the french language. This is a common misconfiguration problem that synchronize translations and not only the "master" language. I will close this issue since I’m sure it’s not a bug in the backend of Accent 😃

**Closed by simonprev** 2024-03-25 01:21 UTC

**Comment by guyaumetremblay** [comment] 2024-03-25 17:04
@simonprev Thanks for your input! It helps me to investigate and you were right... there were a misconfiguration of the Circumflex plugin! 
I just had to put the master language first in the list of locales like this: 
```
locales 'fr', 'en'
```
