### ISSUE TITLE
Cant run the image

### ISSUE THREAD

**Issue by Yggdrasil80** [mirego/accent#300] opened 2022-06-14 15:13 UTC
Hi 👋🏻 
When I run the Docker image, the container crash everytime with this error: ``exec /usr/local/bin/docker-entrypoint.sh: exec format error``
This is my Docker Compose config:
![image](https://user-images.githubusercontent.com/56512795/173613119-9a7a4839-4815-4da2-ba09-078d44b7bb60.png)
And the log:
![image](https://user-images.githubusercontent.com/56512795/173613226-932ba706-396a-4721-b6b6-38857a760630.png)
Thanks for your help 👍🏻

**Comment by simonprev** [comment] 2022-08-29 11:56
This is a duplicate of this: https://github.com/mirego/accent/issues/304

I will do the follow up on this issue instead 👍

**Closed by simonprev** 2022-08-29 11:56 UTC
